<h2><strong>Datos Personales</strong></h2>
<p><strong>Nombre(s) y Apellido(s):</strong> Taliha Cabrera <img src="C:\Users\User\Desktop\photo.jpg" alt="photo" width="112" height="36" /></p>
<p><strong>C&eacute;dula de identidad:</strong> 4.000.001</p>
<p><strong>E-mail:</strong> <a href="mailto:taliha@fpuna.edu.py">taliha@fpuna.edu.py</a></p>
<p><strong>Telefono:</strong> 021 000 0001</p>
<p><strong>Direcci&oacute;n:</strong> Avda. eusebio Ayala</p>
<p><strong>Pasatiempos:</strong>&nbsp;Correr y alpinismo</p>
<p>&nbsp;</p>
<h2><strong>Acad&eacute;mico</strong></h2>
<p><strong>Estudios secundarios:</strong> Bachillerato T&eacute;cnico en Informatica - CMA (2010- 2013)</p>
<p><strong>Estudios universitarios:</strong> Lic. en Ciencias Inform&aacute;ticas - Facultad Polit&eacute;cnica UNA (cursando actualmente)</p>
<p><strong>Idiomas:</strong> Espa&ntilde;ol, guarani e ingl&eacute;s</p>
<p>&nbsp;</p>
<h2><strong>Experiencia Laboral</strong></h2>
<p><strong>Cargo:</strong> Network Center Operation</p>
<p><strong>Funci&oacute;n:</strong> Administrador de sistemas</p>
<p><strong>Antiguedad:</strong> 2.5 a&ntilde;os</p>
<p><strong>Empresa:</strong> Entidad P&uacute;blica</p>
